[book]
authors = ["金磊"]
language = "zh-CN"
multilingual = false
src = "src"
title = "直接核反应理论"
[output.html]
mathjax-support = true
no-section-label = true
additional-css = ["theme/theme.css"]
[preprocessor.katex]
after = ["links"]


